### ISSUE TITLE
Iplayer www v4.1.1 and V4.1.2 problem

### ISSUE THREAD

**Issue by BugfinderPro135** [dimkroon/iplayer_tests#1]
This problem didn't happen in 4.0.17.

It's all based around the fact that there are no tv shows beginning with the letter X.

In settings, set 'Behaviour of getting A-Z' to all-at-once.
In iplayer www, click on 'Programme List A-Z. When it gets to 'x' you get the error '404 Client Error: Not Found for url: https://www.bbc.co.uk/iplayer/a-z/x

and you can't see any programmes listed at all after that.

**Comment by dimkroon** [comment]
I'm not quite sure if you mean that you don't have that problem when you running version 4.0.17 at this moment, or that you didn't have it before the time 4.1.1 was released.

If 4.0.17 still runs fine now, there's probably some bug that has found its way in 4.1.1. If the problem started some time after 4.1.1 was released, then most likely some things have changed at the BBC, either content, or data structure.

Anyway, This repro contains only some tests I use for iplayer www. If you think you've found a bug in the iplayer www addon, you should open an issue at it's [own repo](https://github.com/vonH/plugin.video.iplayerwww).
